"use client";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import { Banner } from "@/components/ui/Banner";
import { Button } from "@/components/ui/Button";
import { Field, Input } from "@/components/ui/Field";
import styles from "./BanUser.module.css";
type Maker={sub:string;name:string;email:string;bannedAt:Date|null;banReason:string|null};
const REASONS=[{value:"fraud",label:"Fraud / manipulation"},{value:"ai",label:"AI policy violation"},{value:"coc",label:"Code of Conduct violation"},{value:"custom",label:"Custom reason"}] as const;
export function BanUser({makers}:{makers:Maker[]}){const router=useRouter();const[query,setQuery]=useState("");const[selected,setSelected]=useState("");const[reasonType,setReasonType]=useState<(typeof REASONS)[number]["value"]>("coc");const[customReason,setCustomReason]=useState("");const[busy,setBusy]=useState(false);const[problem,setProblem]=useState("");const filtered=useMemo(()=>{const n=query.trim().toLowerCase();return n?makers.filter(m=>`${m.name} ${m.email}`.toLowerCase().includes(n)):makers},[makers,query]);const reason=reasonType==="custom"?customReason.trim():reasonType==="fraud"?"Fraud or manipulation of the 3AM program.":reasonType==="ai"?"Violation of the 3AM AI usage policy.":"Violation of the 3AM Code of Conduct.";async function ban(){if(!selected||!reason)return;if(!window.confirm("Ban this account? This immediately blocks access."))return;setBusy(true);setProblem("");const r=await fetch("/api/admin/ban",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userSub:selected,reason})});setBusy(false);if(r.ok){router.refresh();setSelected("");return}const b=(await r.json().catch(()=>({}))) as{message?:string};setProblem(b.message??"The ban did not save.")}return <div className={styles.stack}>{problem?<Banner tone="bad">{problem}</Banner>:null}<div className={styles.search}><Field id="ban-search" label="find maker" help="Search by name or email."><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="name or email"/></Field></div><div className={styles.list}>{filtered.map(m=><button key={m.sub} type="button" className={[styles.maker,selected===m.sub?styles.selected:null,m.bannedAt?styles.banned:null].filter(Boolean).join(" ")} onClick={()=>!m.bannedAt&&setSelected(m.sub)} disabled={Boolean(m.bannedAt)}><span><span className={styles.name}>{m.name}</span><span className={styles.email}>{m.email}</span></span><span className={styles.status}>{m.bannedAt?"banned":"active"}</span></button>)}</div>{selected?<div className={styles.form}><Field id="ban-reason" label="misconduct" help="This exact text is shown on the banned screen."><select className={styles.select} value={reasonType} onChange={e=>setReasonType(e.target.value as typeof reasonType)}>{REASONS.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></Field>{reasonType==="custom"?<Field id="ban-custom" label="custom reason"><Input value={customReason} onChange={e=>setCustomReason(e.target.value)} placeholder="Briefly describe the misconduct."/></Field>:null}<Button onClick={ban} loading={busy} loadingLabel="banning…">❌ ban this maker</Button></div>:null}</div>;}